version: "3"

services:
  app:
    container_name: "collector_service"
    build:
      context: .
      dockerfile: Dockerfile
    image: "collector:v2"
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
      - API_KEY=DEMO_KEY
      - CONCURRENT_REQUESTS=5
